artifactzzz

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,9 +10,22 @@ jobs:
       run: |
           #sudo apt-get install cython
           echo "target_triplet=`gcc -dumpmachine`" >> $GITHUB_ENV
-          run_id=$(curl -fs -H 'Accept: application/vnd.github.antiope-preview+json' https://api.github.com/repos/nikias/libplist/actions/workflows/build.yml/runs \
-              | jq "[.workflow_runs[] | select(.name == \"build\").id][0]")
-          echo $run_id
+    - name: install prebuilt dependencies
+      run: |
+          libplist_artifacts_url=$(curl -fs -H 'Accept: application/vnd.github.antiope-preview+json' https://api.github.com/repos/nikias/libplist/actions/workflows/build.yml/runs \
+              | jq "[.workflow_runs[] | select(.name == \"build\")][0].artifacts_url")
+          echo libplist_artifacts_url
+          if test -z "$libplist_artifacts_url" -o "$libplist_artifacts_url" == "null"; then
+            echo "ERROR: Could not get libplist artifacts URL"
+            exit 1
+          fi
+          libplist_artifact_dl_url="$(curl -s -H 'Accept: application/vnd.github.antiope-preview+json' libplist_artifacts_url \
+              | jq "[.artifacts[] | select(.name == \"libplist-latest_${{env.target_triplet}}\").archive_download_url")
+          if test -z "$libplist_artifact_dl_url" -o "$libplist_artifact_dl_url" == "null"; then
+            echo "ERROR: Could not get artifact archive download URL for ${{env.target_triplet}}"
+            exit 1
+          fi
+          echo "Download URL for ${{env.target_triplet}}: $libplist_artifact_dl_url"
     #- uses: actions/checkout@v2
     #  with:
     #    fetch-depth: 0
