trying this now

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,27 +10,38 @@ jobs:
       run: |
           #sudo apt-get install cython
           echo "target_triplet=`gcc -dumpmachine`" >> $GITHUB_ENV
-    - name: install external dependencies
+    - name: install libplist
+      uses: dawidd6/action-download-artifact@v2
+      with:
+        github_token: ${{secrets.GITHUB_TOKEN}}
+        workflow: build.yml
+        name: libplist-latest_${{env.target_triplet}}
+        path: prebuilt
+        repo: nikias/libplist
+    - name: check results:
       run: |
-          libplist_artifacts_url=$(curl -fs -H 'Accept: application/vnd.github.antiope-preview+json' https://api.github.com/repos/nikias/libplist/actions/workflows/build.yml/runs \
-              | jq "[.workflow_runs[] | select(.name == \"build\")][0].artifacts_url" |xargs)
-          echo $libplist_artifacts_url
-          if test -z "$libplist_artifacts_url" -o "$libplist_artifacts_url" == "null"; then
-            echo "ERROR: Could not get libplist artifacts URL"
-            exit 1
-          fi
-          libplist_artifact_dl_url=$(curl -s -H 'Accept: application/vnd.github.antiope-preview+json' $libplist_artifacts_url \
-              | jq ".artifacts[] | select(.name == \"libplist-latest_${{env.target_triplet}}\").archive_download_url" |xargs)
-          echo $libplist_artifact_dl_url
-          if test -z "$libplist_artifact_dl_url" -o "$libplist_artifact_dl_url" == "null"; then
-            echo "ERROR: Could not get artifact archive download URL for ${{env.target_triplet}}"
-            exit 1
-          fi
-          echo "Download URL for ${{env.target_triplet}}: $libplist_artifact_dl_url"
-          libplist_artifact_base_url=$(echo $libplist_artifact_dl_url |sed 's/https:\/\///')
-          curl -L -s -o libplist.zip "https://${{secrets.GITHUB_TOKEN}}@$libplist_artifact_base_url"
-          cat libplist.zip
-          unzip -l libplist.zip
+          ls -l prebuilt
+    #- name: install external dependencies
+    #  run: |
+    #      libplist_artifacts_url=$(curl -fs -H 'Accept: application/vnd.github.antiope-preview+json' https://api.github.com/repos/nikias/libplist/actions/workflows/build.yml/runs \
+    #          | jq "[.workflow_runs[] | select(.name == \"build\")][0].artifacts_url" |xargs)
+    #      echo $libplist_artifacts_url
+    #      if test -z "$libplist_artifacts_url" -o "$libplist_artifacts_url" == "null"; then
+    #        echo "ERROR: Could not get libplist artifacts URL"
+    #        exit 1
+    #      fi
+    #      libplist_artifact_dl_url=$(curl -s -H 'Accept: application/vnd.github.antiope-preview+json' $libplist_artifacts_url \
+    #          | jq ".artifacts[] | select(.name == \"libplist-latest_${{env.target_triplet}}\").archive_download_url" |xargs)
+    #      echo $libplist_artifact_dl_url
+    #      if test -z "$libplist_artifact_dl_url" -o "$libplist_artifact_dl_url" == "null"; then
+    #        echo "ERROR: Could not get artifact archive download URL for ${{env.target_triplet}}"
+    #        exit 1
+    #      fi
+    #      echo "Download URL for ${{env.target_triplet}}: $libplist_artifact_dl_url"
+    #      libplist_artifact_base_url=$(echo $libplist_artifact_dl_url |sed 's/https:\/\///')
+    #      curl -L -s -o libplist.zip "https://${{secrets.GITHUB_TOKEN}}@$libplist_artifact_base_url"
+    #      cat libplist.zip
+    #      unzip -l libplist.zip
     #- uses: actions/checkout@v2
     #  with:
     #    fetch-depth: 0
